### ISSUE TITLE
Change metadata so that better content is displayed when shared in social media

### ISSUE THREAD

**Issue by ceilican** [DjedAlliance/Djed-Solidity-WebDashboard#103]
This is how the web dashboard is displayed when shared in Discord:

<img width="403" alt="Screenshot 2024-04-08 at 20 13 01" src="https://github.com/DjedAlliance/Djed-Solidity-WebDashboard/assets/1809436/e17a80aa-dc07-45bb-8ff0-77afff5f42ca">

We need to improve this.

**Comment by a-singh09** [comment]
Hi, i would like to work on this issue, can you assign this to me?

**Comment by ceilican** [comment]
Hi @a-singh09 , I assigned this issue to you, as requested.

Ideally, we should take the metadata from variables in the env file, since we might want to customize the metadata for each different deployment.
