### ISSUE TITLE
"Pending Confirmation" modal never disappears

### ISSUE THREAD

**Issue by ceilican** [DjedAlliance/Djed-Solidity-WebDashboard#104]
In Sepolia, the "Pending Confirmation" modal keeps waiting forever, even after the transaction has already been confirmed.

<img width="1211" alt="Screenshot 2024-04-08 at 20 16 48" src="https://github.com/DjedAlliance/Djed-Solidity-WebDashboard/assets/1809436/921dfda0-c08b-45d9-a96a-0b8290982a4d">

**Comment by Ronnieraj37** [comment]
Hey @ceilican Can I work on this ?
