### ISSUE TITLE
Refreshing prices frequently causes Infura's free API limits to be reached

### ISSUE THREAD

**Issue by ceilican** [DjedAlliance/Djed-Solidity-WebDashboard#105]
<img width="627" alt="Screenshot 2024-04-09 at 19 28 40" src="https://github.com/DjedAlliance/Djed-Solidity-WebDashboard/assets/1809436/b60df076-71ca-4312-bf2a-e8324ce2e3f6">

We didn't have a problem when we had only a deployment for Milkomeda, because the Milkomeda API is free. But, with the deployment for Sepolia, the Infura API has a limit of calls in its free API. It suffices for a single user to forget a tab with https://sepolia.djed.one open for the daily limit to be almost reached. This occurs because we are fetching the price at regular intervals, even when the user's tab is inactive.

Ideally, we should detect whether the tab is active or not and only update the price when it is active.

**Comment by Tanya-ruby** [comment]
I would like to work on this !Can I get this assigned? @ceilican
