### ISSUE TITLE
Decimals of base coin should be fetched from the blockchain, instead of hard-coded

### ISSUE THREAD

**Issue by ceilican** [DjedAlliance/Djed-Solidity-WebDashboard#115]
This line (https://github.com/DjedAlliance/Djed-Solidity-WebDashboard/blob/963655e62828d4b2927edfcff9bddfad67ad258d/src/utils/ethereum.js#L26C1-L26C31) should be fixed. we should not have a magical number there.

```
export const BC_DECIMALS = 18;
```

**Comment by ceilican** [comment]
Thanks, @NeeL1249 .

**Comment by ceilican** [comment]
Contact me in discord.

**Comment by NeeL1249** [comment]
Hey, Where can i get your discord id?
