### ISSUE TITLE
Link to Deployment in Explorer is Undefined

### ISSUE THREAD

**Issue by ceilican** [DjedAlliance/Djed-Solidity-WebDashboard#133]
<img width="577" alt="Screenshot 2024-12-20 at 20 33 31" src="https://github.com/user-attachments/assets/f77b2d0b-4fd4-4c8c-a654-3c0d20a4a57c" />

This is occurring only for https://etc.djed.one .

It is not occurring for https://milkomeda-c1.djed.one .

The URL of the Ethereum Classic explorer is probably missing in the environment file for Ethereum Classic.

**Comment by kumawatkaran523** [comment]
@ceilican Please Assign to me
