### ISSUE TITLE
Do QA of the Wrapped Smart Contract feature in milkomeda-c1-testnet.djed.one

### ISSUE THREAD

**Issue by ceilican** [DjedAlliance/Djed-Solidity-WebDashboard#64]

**Comment by ceilican** [comment]
What to test:

- [ ] Try to Buy Stablecoins
- [ ] Try to Sell Stabelcoins
- [ ] Try to Buy Reservecoins
- [ ] Try to Sell Reservecoins

All these tests should be performed with a native cardano wallet, using ADA, instead of mADA.

**Comment by roxor-dj** [comment]
**Wallet:** MetaMask version 10.31.0 
**Browser:** GoogleChrome

**Successfully bought stablecoin**

`https://explorer-mainnet-cardano-evm.c1.milkomeda.com/tx/0xeca0e6e92f59ae9632c9bf14dfd87d46458ca70d09e64df3c973a876ccc2c5ba/token-transfers`

![stableBUY](https://github.com/DjedAlliance/Djed-Solidity-WebDashboard/assets/43718866/cfca0be6-286a-4fff-9637-c133c6d51b1c)

**Successfully sold stable**

`https://explorer-mainnet-cardano-evm.c1.milkomeda.com/tx/0xe78f619ea33aa3d22ce078de3a99620066e2a4bab72bfde85ef111e334b295db/token-transfers`

![stableSell](https://github.com/DjedAlliance/Djed-Solidity-WebDashboard/assets/43718866/cfc5509c-04c9-4b99-82df-3b9e3edb2441)


**Successfully bought Reservcoins**

`https://explorer-mainnet-cardano-evm.c1.milkomeda.com/tx/0x6f2565846b7fb428a03758dff12c5eb07f96d7cc954ef7d0d424cb0b7d710def/token-transfers`

![BUY](https://github.com/DjedAlliance/Djed-Solidity-WebDashboard/assets/43718866/b6895f7c-c447-4a07-a8ad-6e9cceb51629)


**Successfully sold Reservcoins**

`https://explorer-mainnet-cardano-evm.c1.milkomeda.com/tx/0x10e7857e1f64675f719794f7844ae41655786728819dcb43e2ab8e4da31f1e6c/token-transfers`

![sell](https://github.com/DjedAlliance/Djed-Solidity-WebDashboard/assets/43718866/f3e007c4-22b4-4be4-9e38-e7298abc06fa)
