### ISSUE TITLE
Fix the failing tests

### ISSUE THREAD

**Issue by ceilican** [DjedAlliance/Djed-Solidity-WebDashboard#69]
Message from @AlexITC in #68 :  Tests are failing but I'm not the adequate person to fix those, see https://github.com/DjedAlliance/Djed-Solidity-WebDashboard/actions/runs/5129021520/jobs/9226252308?pr=68 .

Once the tests are passing, uncomment lines 36--38 in `.github/workflows/ci.yml`

**Comment by SimardeepSingh1450** [comment]
@ceilican Assign me this issue, I will try to resolve this, if not possible from my end, will update you about it.

**Comment by ceilican** [comment]
Thanks, @SimardeepSingh1450 ! I assigned it to you. Looking forward to receiving your PR.

**Comment by ceilican** [comment]
@SimardeepSingh1450 , are you still working on this issue?

**Comment by Ronnieraj37** [comment]
Hey @ceilican the logs for this have expired. Is this issue a part of #98 ?

**Comment by ceilican** [comment]
Oh. I did not know the logs could expire. Next time I will include a screenshot of the log. Unfortunately, I don't remember what these logs were showing. 

In any case, @Ronnieraj37 , could you generally check if all tests are passing? If they are, we can close this issue.

**Comment by ceilican** [comment]
Fixed by #111 .
