### ISSUE TITLE
Upgrade node version to 18

### ISSUE THREAD

**Issue by ceilican** [DjedAlliance/Djed-Solidity-WebDashboard#75]

**Comment by ceilican** [comment]
Make sure all dependencies are working.

We need to wait for `milkomeda-c1-testnet` to be merged to `main` first, because I think some changes were already made there that make it work with node 18.

**Comment by ceilican** [comment]
cc: @AlexITC .

**Comment by KENILSHAHH** [comment]
Hey @ceilican would like to work on this issue, can you please assign it to me

**Comment by ceilican** [comment]
Hi @KENILSHAHH . See my comment above from 1st of June. This issue is blocked. I will assign it to you when it becomes available, which should happen soon. In the meantime, would you like to choose another issue?

**Comment by ceilican** [comment]
@KENILSHAHH @sagardxd , I have assigned this issue to both of you. Please help each other and divide the work among each other. Or, if there is not enough work to divide, we can assign one of you to another issue.

**Comment by ceilican** [comment]
> We need to wait for milkomeda-c1-testnet to be merged to main first

This has not happened yet. But let's proceed anyway. Have a look on that branch, because it may contain useful changes.

**Comment by keshav-nischal** [comment]
@ceilican i would like to work on this issue. Why we are not upgrading to node-20??

**Comment by ceilican** [comment]
Yes, node-20 would be even better. I will assign it to you.

**Comment by ceilican** [comment]
@Ronnieraj37 , i think your latest PR closes this, right?

**Comment by ceilican** [comment]
Closed by #111 .
