### ISSUE TITLE
Price feeds for sepolia network are not displayed on WebDashboard

### ISSUE THREAD

**Issue by yogesh0509** [DjedAlliance/Djed-Solidity-WebDashboard#97]
Debug the issue with the price feeds and smart contracts integration on the Sepolia testnet. Ensure that data from the smart contract is being fetched correctly on the web dashboard and displayed accurately. If needed, refer to the Milkomeda testnet for guidance.

**Comment by ceilican** [comment]
@Tanya-ruby

**Comment by ceilican** [comment]
@yogesh0509 , for some reason, I'm not managing to assign @Tanya-ruby to this issue.

**Comment by yogesh0509** [comment]
@ceilican even I can't assign it to her. Did this ever happen before?

**Comment by ceilican** [comment]
@Tanya-ruby , could you write a comment here, so that we can see whether we can assign the issue to you after you comment?

**Comment by Tanya-ruby** [comment]
@ceilican ,can I get this issue assigned ?

**Comment by yogesh0509** [comment]
@Tanya-ruby I have assigned you the issue.

**Comment by Tanya-ruby** [comment]
<img width="1440" alt="Screenshot 2024-03-18 at 8 12 53 AM" src="https://github.com/DjedAlliance/Djed-Solidity-WebDashboard/assets/157852043/a25657aa-b6c3-4b96-ab54-f7b4c21bc614">

@yogesh0509 only the unscaled price of the stable coin is fetched but not converted properly,What about the other values pertaining to reserve coin,base coin?Are they supposed to have those values when fetched?

**Comment by yogesh0509** [comment]
I think the issue is regarding decimals as decimals for milkomeda and sepolia are different. Maybe we can set decimals in the env file. What do you think? @ceilican

**Comment by Tanya-ruby** [comment]
<img width="1440" alt="milkomeda" src="https://github.com/DjedAlliance/Djed-Solidity-WebDashboard/assets/157852043/6a98ba53-8e92-4d47-8dd4-fdc2f4d86bb9">
<img width="1440" alt="milkomeda-testnet" src="https://github.com/DjedAlliance/Djed-Solidity-WebDashboard/assets/157852043/14f85a65-7abc-4368-886e-898a0302612e">
<img width="1440" alt="sepolia-testnet" src="https://github.com/DjedAlliance/Djed-Solidity-WebDashboard/assets/157852043/3747e93b-7b83-4704-b24a-c99af15c2dec">
@ceilican

**Comment by ceilican** [comment]
Also, in the Sepolia screenshot, we have "= 106,000,000,000 mADA". It should be "ETH" instead of "mADA". This "mADA" probably hard-coded in the frontend at the moment, but the frontend should be taking the currency symbol from env file instead. Could you also fix this as part of this PR, @Tanya-ruby ?

**Comment by ceilican** [comment]
> This is probably because I only bought stable coins and not any reserve coin.

@yogesh0509 , and did you deposit any sETH into the contract when you deployed it or after deploying it? I'm asking because the screenshot shows that the reserve's balance is 1.09 ETH and the reserve ratio is about 1000%. So, there is approximately 1 ETH of reserve surplus.

@yogesh0509 @Tanya-ruby , could one of you buy some reservecoins, just so we see what happens?

**Comment by yogesh0509** [comment]
> > This is probably because I only bought stable coins and not any reserve coin.
> 
> @yogesh0509 , and did you deposit any sETH into the contract when you deployed it or after deploying it? I'm asking because the screenshot shows that the reserve's balance is 1.09 ETH and the reserve ratio is about 1000%. So, there is approximately 1 ETH of reserve surplus.
> 
> @yogesh0509 @Tanya-ruby , could one of you buy some reservecoins, just so we see what happens?

Yes I deposited 1ETH upon deployment as the same was done for tests.

**Comment by ceilican** [comment]
OK. Then let's mint some reservecoins and see what happens.

**Comment by Tanya-ruby** [comment]
> > Also, in the Sepolia screenshot, we have "= 106,000,000,000 mADA". It should be "ETH" instead of "mADA". This "mADA" probably hard-coded in the frontend at the moment, but the frontend should be taking the currency symbol from env file instead. Could you also fix this as part of this PR, @Tanya-ruby ?
> 
> Okay!I've made all the changes .If yes ,I'll make the PR for the same ! Also I changed the mADA symbol to ETH ,the underlying conversion is from the getScAdaEquivalent function itself,which was defined earlier. @ceilican 

@ceilican I've updated the PR reflecting all these changes
